-- =============================================================================
-- 06_content_tables.sql  —  Apex Athletics Content Supply Chain
-- Creates: CAMPAIGN_BRIEFS, CONTENT_ASSETS, CAMPAIGN_AUDIENCES
-- These tables are populated by Writer via MCP during the demo.
-- Schemas must match exactly what the stored procedures expect.
-- =============================================================================

USE ROLE SYSADMIN;
USE WAREHOUSE WRITER_WH;
USE SCHEMA WRITER_SNOW_DEMO.MARKETING;

-- ---------------------------------------------------------------------------
-- CAMPAIGN_BRIEFS — Writer generates and writes these back via MCP save-brief
-- ---------------------------------------------------------------------------
CREATE OR REPLACE TABLE WRITER_SNOW_DEMO.MARKETING.CAMPAIGN_BRIEFS (
  BRIEF_ID                    VARCHAR(30)   NOT NULL,
  CAMPAIGN_ID                 VARCHAR(15),
  AUDIENCE_SEGMENT_ID         VARCHAR(10),
  PERSONA_NAME                VARCHAR(100),
  OBJECTIVE                   VARCHAR(30),   -- awareness/consideration/conversion/retention
  TARGET_AUDIENCE_DESCRIPTION VARCHAR(500),
  KEY_MESSAGES                ARRAY,
  TONE                        VARCHAR(50),
  CHANNELS                    ARRAY,
  PRIMARY_KPI                 VARCHAR(50),
  KPI_TARGET                  VARCHAR(50),
  MANDATORY_INCLUSIONS        VARCHAR(300),
  PROHIBITED_CONTENT          VARCHAR(300),
  PRODUCT_FOCUS               VARCHAR(10),
  INSPIRATION_CAMPAIGN_IDS    ARRAY,
  BRAND_VOICE_NOTES           VARCHAR(500),
  STATUS                      VARCHAR(20)   DEFAULT 'draft',  -- draft/approved/archived
  CREATED_BY                  VARCHAR(50),
  CREATED_AT                  TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  APPROVED_AT                 TIMESTAMP_NTZ
);

-- Write-back table: Writer needs SELECT + INSERT
GRANT SELECT, INSERT ON TABLE WRITER_SNOW_DEMO.MARKETING.CAMPAIGN_BRIEFS TO ROLE WRITER_MARKETING_ROLE;

-- ---------------------------------------------------------------------------
-- CONTENT_ASSETS — Writer generates and writes these back via MCP save-asset
-- One row per discrete marketing asset generated by Writer
-- ---------------------------------------------------------------------------
CREATE OR REPLACE TABLE WRITER_SNOW_DEMO.MARKETING.CONTENT_ASSETS (
  ASSET_ID          VARCHAR(30)   NOT NULL,
  BRIEF_ID          VARCHAR(30),
  CAMPAIGN_ID       VARCHAR(15),
  ASSET_TYPE        VARCHAR(30),   -- subject_line/email_body/social_post/ad_copy/landing_page/sms/push/blog
  CHANNEL           VARCHAR(20),   -- email/linkedin/meta/google/tiktok/sms/push/blog/web
  CONTENT_BODY      VARCHAR(10000),
  HEADLINE          VARCHAR(200),
  CTA               VARCHAR(100),
  APPROVAL_STATUS   VARCHAR(20)   DEFAULT 'draft',  -- draft/in_review/approved/published/archived
  BRAND_VOICE_SCORE NUMBER(4,2),
  GENERATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  REVIEWED_BY       VARCHAR(100),
  REVIEWED_AT       TIMESTAMP_NTZ,
  PUBLISHED_AT      TIMESTAMP_NTZ,
  PUBLISHED_URL     VARCHAR(500)
);

-- Write-back table: Writer needs SELECT + INSERT
GRANT SELECT, INSERT ON TABLE WRITER_SNOW_DEMO.MARKETING.CONTENT_ASSETS TO ROLE WRITER_MARKETING_ROLE;

-- ---------------------------------------------------------------------------
-- CAMPAIGN_AUDIENCES — Activation staging table (Reverse ETL target)
-- Written by ACTIVATE_SEGMENT stored procedure
-- Reverse ETL reads WHERE STATUS = 'pending' to push to Braze/SFMC
-- ---------------------------------------------------------------------------
CREATE OR REPLACE TABLE WRITER_SNOW_DEMO.MARKETING.CAMPAIGN_AUDIENCES (
  AUDIENCE_ID           NUMBER AUTOINCREMENT PRIMARY KEY,
  SEGMENT_ID            NUMBER        NOT NULL,
  SEGMENT_NAME          VARCHAR(200)  NOT NULL,
  CUSTOMER_ID           VARCHAR(12)   NOT NULL,
  EMAIL                 VARCHAR(100),
  FIRST_NAME            VARCHAR(50),
  PREFERRED_CHANNEL     VARCHAR(20),
  CAMPAIGN_NAME         VARCHAR(100)  NOT NULL,
  CAMPAIGN_CONTENT_ID   VARCHAR(30),   -- FK → CONTENT_ASSETS.ASSET_ID
  PRIORITY_RANK         NUMBER,
  STATUS                VARCHAR(20)   DEFAULT 'pending',  -- pending/activated/suppressed
  CREATED_AT            TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  ACTIVATED_AT          TIMESTAMP_NTZ
);

-- Write-back table: ACTIVATE_SEGMENT proc writes here; Writer reads results
GRANT SELECT, INSERT ON TABLE WRITER_SNOW_DEMO.MARKETING.CAMPAIGN_AUDIENCES TO ROLE WRITER_MARKETING_ROLE;
